require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DirectionsController do

  # This should return the minimal set of attributes required to create a valid
  # Direction. As you add validations to Direction, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DirectionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all directions as @directions" do
      direction = Direction.create! valid_attributes
      get :index, {}, valid_session
      assigns(:directions).should eq([direction])
    end
  end

  describe "GET show" do
    it "assigns the requested direction as @direction" do
      direction = Direction.create! valid_attributes
      get :show, {:id => direction.to_param}, valid_session
      assigns(:direction).should eq(direction)
    end
  end

  describe "GET new" do
    it "assigns a new direction as @direction" do
      get :new, {}, valid_session
      assigns(:direction).should be_a_new(Direction)
    end
  end

  describe "GET edit" do
    it "assigns the requested direction as @direction" do
      direction = Direction.create! valid_attributes
      get :edit, {:id => direction.to_param}, valid_session
      assigns(:direction).should eq(direction)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Direction" do
        expect {
          post :create, {:direction => valid_attributes}, valid_session
        }.to change(Direction, :count).by(1)
      end

      it "assigns a newly created direction as @direction" do
        post :create, {:direction => valid_attributes}, valid_session
        assigns(:direction).should be_a(Direction)
        assigns(:direction).should be_persisted
      end

      it "redirects to the created direction" do
        post :create, {:direction => valid_attributes}, valid_session
        response.should redirect_to(Direction.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved direction as @direction" do
        # Trigger the behavior that occurs when invalid params are submitted
        Direction.any_instance.stub(:save).and_return(false)
        post :create, {:direction => {}}, valid_session
        assigns(:direction).should be_a_new(Direction)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Direction.any_instance.stub(:save).and_return(false)
        post :create, {:direction => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested direction" do
        direction = Direction.create! valid_attributes
        # Assuming there are no other directions in the database, this
        # specifies that the Direction created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Direction.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => direction.to_param, :direction => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested direction as @direction" do
        direction = Direction.create! valid_attributes
        put :update, {:id => direction.to_param, :direction => valid_attributes}, valid_session
        assigns(:direction).should eq(direction)
      end

      it "redirects to the direction" do
        direction = Direction.create! valid_attributes
        put :update, {:id => direction.to_param, :direction => valid_attributes}, valid_session
        response.should redirect_to(direction)
      end
    end

    describe "with invalid params" do
      it "assigns the direction as @direction" do
        direction = Direction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Direction.any_instance.stub(:save).and_return(false)
        put :update, {:id => direction.to_param, :direction => {}}, valid_session
        assigns(:direction).should eq(direction)
      end

      it "re-renders the 'edit' template" do
        direction = Direction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Direction.any_instance.stub(:save).and_return(false)
        put :update, {:id => direction.to_param, :direction => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested direction" do
      direction = Direction.create! valid_attributes
      expect {
        delete :destroy, {:id => direction.to_param}, valid_session
      }.to change(Direction, :count).by(-1)
    end

    it "redirects to the directions list" do
      direction = Direction.create! valid_attributes
      delete :destroy, {:id => direction.to_param}, valid_session
      response.should redirect_to(directions_url)
    end
  end

end
